In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import layers, losses
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Model, load_model

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

import seaborn as sns
import re
import datetime
import os
import shutil

%matplotlib inline

In [ ]:
%tensorflow_version 2.x
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
from google.colab import drive
import glob
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Data 전처리

In [ ]:
csv_path = '/content/drive/MyDrive/CIC/csv'
done_path = '/content/drive/MyDrive/CIC/done/'
all_files = glob.glob(csv_path + "/*.csv")

In [ ]:
for filename in all_files:
  data = pd.read_csv(filename)
  #shutil.move(filename, done_path )
  break

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 84 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Flow ID                     2925 non-null   object 
 1   Src IP                      2925 non-null   object 
 2   Src Port                    2925 non-null   int64  
 3   Dst IP                      2925 non-null   object 
 4   Dst Port                    2925 non-null   int64  
 5   Protocol                    2925 non-null   int64  
 6   Timestamp                   2925 non-null   object 
 7   Flow Duration               2925 non-null   int64  
 8   Total Fwd Packet            2925 non-null   int64  
 9   Total Bwd packets           2925 non-null   int64  
 10  Total Length of Fwd Packet  2925 non-null   float64
 11  Total Length of Bwd Packet  2925 non-null   float64
 12  Fwd Packet Length Max       2925 non-null   float64
 13  Fwd Packet Length Min       2925 

In [ ]:
data.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Len

In [ ]:
data["Timestamp"] = data["Timestamp"].str.replace('오전', 'AM',regex=True).replace('오후', 'PM',regex=True)

In [ ]:
data["Timestamp"] = pd.to_datetime(data["Timestamp"])

In [ ]:
data["Timestamp"]

0      2022-02-28 12:32:16
1      2022-02-28 12:32:23
2      2022-02-28 12:32:30
3      2022-02-28 12:32:34
4      2022-02-28 12:32:37
               ...        
2920   2022-02-28 12:42:53
2921   2022-02-28 12:40:36
2922   2022-02-28 12:32:55
2923   2022-02-28 12:39:35
2924   2022-02-28 12:42:59
Name: Timestamp, Length: 2925, dtype: datetime64[ns]

## Protocol

In [ ]:
protocol_value = {
      0 : 'HOPPORT',
      1 : 'ICMP',
      2 : 'IGMP',
      3 : 'GGP',
      4 : 'IPv4',
      5 : 'ST',
      6 : 'TCP',
      7 : 'CBT',
      8 : 'EGP',
      9 : 'IGP',
      10 : '	BBN-RCC-MON',
      11 : 'NVP-II',
      12 : 'PUP',
      13 : 'ARGUS',
      14 : 'EMCON',
      15 : 'XNET',
      16 : 'CHAOS',
      17 : 'UDP',
      18 : 'MUX',
      19 : 'DCN-MEAS',
      20 : 'HMP',
      21 : 'PRM',
      22 : 'XNS-IDP',
      23 : 'TRUNK-1',
      24 : 'TRUNK-2',
      25 : 'LEAF-1',
      26 : 'LEAF-2',
      27 : 'RDP',
      28 : 'IRTP',
      29 : 'ISO-TP4',
      30 : 'NETBLT',
      31 : 'MFE-NSP',
      32 : 'MERIT-INP',
      33 : 'DCCP',
      34 : '3PC',
      35 : 'IDPR',
      36 : 'XTP',
      37 : 'DDP',
      38 : 'IDPR-CMTP',
      39 : 'TP++',
      40 : 'IL',
      41 : 'IPv6',
      42 : 'SDRP',
      43 : 'IPv6-Route',
      44 : 'IPv6-Frag',
      45 : 'IDRP',
      46 : 'RSVP',
      47 : 'GRE',
      48 : 'DSR',
      49 : 'BNA',
      50 : 'ESP',
      51 : 'AH',
      52 : 'I-NLSP',
      53 : 'SWIPE',
      54 : 'NARP',
      55 : 'MOBILE',
      56 : 'TSLP',
      57 : 'SKIP',
      58 : 'IPv6-ICMP',
      59 : 'IPv6-NoNxt',
      60 : 'IPv6-Opts',
      61 : 'UNKNOWN',
      62 : 'CFTP',
      63 : 'UNKNOWN',
      64 : 'SAT-EXPAK',
      65 : 'KRYPTOLAN',
      66 : 'RVD',
      67 : 'IPPC',
      68 : 'UNKNOWN',
      69 : 'SAT-MON',
      70 : 'VISA',
      71 : 'IPCV',
      72 : 'CPNX',
      73 : 'CPHB',
      74 : 'WSN',
      75: 'PVP',
      76 : 'BR-SAT-MON',
      77 : 'SUN-ND',
      78 : 'WB-MON',
      79 : 'WB-EXPAK',
      80 : 'ISO-IP',
      81 : 'VMTP', 
      82 : 'SECURE-VMTP',
      83 : 'VINES',
      84 : 'TTP/IPTM',
      85 : 'NSFNET-IGP',
      86 : 'DGP',
      87 : 'TCF',
      88 : 'EIGRP',
      89 : 'OSPF',
      90 : 'Sprite-RPC',
      91 : 'LARP',
      92 : 'MTP',
      93 : 'AX.25',
      94 : 'OS',
      95 : 'MICP',
      96 : 'SCC-SP',
      97 : 'ETHERIP',
      98 : 'ENCAP',
      99 : 'UNKNOWN',
      100 : 'GMTP',
      101 : 'IFMP',
      102 : 'PNNI',
      103 : 'PIM',
      104 : 'ARIS',
      105 : 'SCPS',
      106 : 'QNX',
      107 : 'A/N',
      108 : 'IPComp',
      109 : 'SNP',
      110 : 'Compaq-Peer',
      111 : 'IPX-in-IP',
      112 : 'VRRP',
      113 : 'PGM',
      114 : 'UNKNOWN',
      115 : 'L2TP',
      116 : 'DDX', 
      117 : 'IATP',
      118 : 'STP',
      119 : 'SRP',
      120 : 'UTI',
      121 : 'SMP',
      122 : 'SM',
      123 : 'PTP',
      124 : 'IS-IS over IPv4',
      125 : 'FIRE',
      126 : 'CRTP',
      127 : 'CRUDP',
      128 : 'SSCOPMCE',
      129 : 'IPLT',
      130 : 'SPS',
      131 : 'PIPE',
      132 : 'SCTP',
      133 : 'FC',
      134 : 'RSVP-E2E-IGNORE',
      135 : 'Mobility Header',
      136 : 'UDPLite',
      137 : 'MPLS-in-IP',
      138 : 'manet',
      139 : 'HIP',
      140 : 'Shim6',
      141 : 'WESP',
      142 : 'ROHC',
      143 : 'Ethernet',
      253 : 'UNKNOWN',
      254 : 'UNKNOWN', 
      255 : 'Reserved'

}

data = data.replace({'Protocol' : protocol_value})

## Data Frame

In [ ]:
data.head()

Flow ID         Src IP  Src Port  \
0    192.168.1.111-52.72.75.234-55667-443-6  192.168.1.111     55667   
1    192.168.1.111-52.72.75.234-55669-443-6  192.168.1.111     55669   
2    192.168.1.111-52.72.75.234-55670-443-6  192.168.1.111     55670   
3  192.168.1.133-192.168.1.111-60511-7680-6  192.168.1.133     60511   
4    192.168.1.111-52.72.75.234-55672-443-6  192.168.1.111     55672   

          Dst IP  Dst Port Protocol           Timestamp  Flow Duration  \
0   52.72.75.234       443      TCP 2022-02-28 12:32:16        1184617   
1   52.72.75.234       443      TCP 2022-02-28 12:32:23        1192442   
2   52.72.75.234       443      TCP 2022-02-28 12:32:30        1191315   
3  192.168.1.111      7680      TCP 2022-02-28 12:32:34           3376   
4   52.72.75.234       443      TCP 2022-02-28 12:32:37        1176575   

   Total Fwd Packet  Total Bwd packets  ...  Fwd Seg Size Min  Active Mean  \
0                12                 14  ...                20          0.0   
1                13                 15  ...                20          0.0   
2                12                 15  ...                20          0.0   
3                 3                  2  ...                20          0.0   
4                12                 14  ...                20          0.0   

   Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  \
0         0.0         0.0         0.0        0.0       0.0       0.0   
1         0.0         0.0         0.0        0.0       0.0       0.0   
2         0.0         0.0         0.0        0.0       0.0       0.0   
3         0.0         0.0         0.0        0.0       0.0       0.0   
4         0.0         0.0         0.0        0.0       0.0       0.0   

   Idle Min            Label  
0       0.0  NeedManualLabel  
1       0.0  NeedManualLabel  
2       0.0  NeedManualLabel  
3       0.0  NeedManualLabel  
4       0.0  NeedManualLabel  

[5 rows x 84 columns]

In [ ]:
details = ["Timestamp", "Src IP", "Src Port", "Dst IP", "Dst Port", "Protocol"]

In [ ]:
main_features = ["Flow Duration", "Flow Bytes/s", "Flow Packets/s", "Flow IAT Mean",
                 "Fwd IAT Mean", "Bwd IAT Mean", "Active Mean", "Idle Mean"]

In [ ]:
dataset = data[main_features]

In [ ]:
Z = data[details]

In [ ]:
label_train = data.drop(["Flow ID", "Src IP", "Src Port", "Dst IP", "Protocol", "Timestamp", "Label"], axis=1)

In [ ]:
Z.head()

Timestamp         Src IP  Src Port         Dst IP  Dst Port  \
0 2022-02-28 12:32:16  192.168.1.111     55667   52.72.75.234       443   
1 2022-02-28 12:32:23  192.168.1.111     55669   52.72.75.234       443   
2 2022-02-28 12:32:30  192.168.1.111     55670   52.72.75.234       443   
3 2022-02-28 12:32:34  192.168.1.133     60511  192.168.1.111      7680   
4 2022-02-28 12:32:37  192.168.1.111     55672   52.72.75.234       443   

  Protocol  
0      TCP  
1      TCP  
2      TCP  
3      TCP  
4      TCP

In [ ]:
dataset.head()

Flow Duration  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  Fwd IAT Mean  \
0        1184617   7258.886205       21.948022   47384.680000  90111.727273   
1        1192442   7211.252203       23.481226   44164.518519  83144.833333   
2        1191315   7218.074145       22.664031   45819.807692  90677.090909   
3           3376  22215.639810     1481.042654     844.000000   1599.500000   
4        1176575   7308.501371       22.098039   47063.000000  89583.818182   

   Bwd IAT Mean  Active Mean  Idle Mean  
0  76293.307692          0.0        0.0  
1  71241.714286          0.0        0.0  
2  71319.571429          0.0        0.0  
3   3283.000000          0.0        0.0  
4  75828.538462          0.0        0.0

In [ ]:
dataset = dataset.apply(pd.to_numeric, errors='coerce')

In [ ]:
label_train = label_train.apply(pd.to_numeric, errors='coerce')

In [ ]:
dataset = dataset.dropna(axis=0)

In [ ]:
label_train = label_train.dropna(axis=0)

In [ ]:
dataset = dataset.replace([np.inf, -np.inf], np.nan)
dataset.dropna(inplace = True)

In [ ]:
label_train = label_train.replace([np.inf, -np.inf], np.nan)
label_train.dropna(inplace = True)

In [ ]:
dataset

Flow Duration  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  \
0           1184617   7258.886205       21.948022   47384.680000   
1           1192442   7211.252203       23.481226   44164.518519   
2           1191315   7218.074145       22.664031   45819.807692   
3              3376  22215.639810     1481.042654     844.000000   
4           1176575   7308.501371       22.098039   47063.000000   
...             ...           ...             ...            ...   
2920         305095    144.217375        6.555335  305095.000000   
2921         306310    215.467990        6.529333  306310.000000   
2922         313221    140.475894        6.385268  313221.000000   
2923         311544    141.232057        6.419639  311544.000000   
2924              9      0.000000   333333.333333       4.500000   

       Fwd IAT Mean  Bwd IAT Mean  Active Mean  Idle Mean  
0      90111.727273  76293.307692          0.0        0.0  
1      83144.833333  71241.714286          0.0        0.0  
2      90677.090909  71319.571429          0.0        0.0  
3       1599.500000   3283.000000          0.0        0.0  
4      89583.818182  75828.538462          0.0        0.0  
...             ...           ...          ...        ...  
2920  305095.000000      0.000000          0.0        0.0  
2921  306310.000000      0.000000          0.0        0.0  
2922  313221.000000      0.000000          0.0        0.0  
2923  311544.000000      0.000000          0.0        0.0  
2924       0.000000      1.000000          0.0        0.0  

[2925 rows x 8 columns]

In [ ]:
scaler = MinMaxScaler()
scaler.fit(dataset)
dataset = scaler.transform(dataset)

In [ ]:
scaler = MinMaxScaler()
scaler.fit(label_train)
label_train = scaler.transform(label_train)

In [ ]:
sorted_feature = sorted(np.unique(dataset[:,0]))
sorted_feature[0], sorted_feature[-1]

(0.0, 1.0)

In [ ]:
sorted_label = sorted(np.unique(label_train[:,0]))
sorted_label[0], sorted_label[-1]

(0.0, 1.0)

## Autoencoder

In [ ]:
model_path = '/content/drive/MyDrive/MODEL_TEST/autoencoder.h5'
autoencoder = load_model (model_path)

In [ ]:
model_path = '/content/drive/MyDrive/MODEL_TEST/AEwithLabel.h5'
labelmodel = load_model (model_path)

In [ ]:
autoencoder.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 8)]               0         
                                                                 
 dense (Dense)               (None, 4)                 36        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
 dense_2 (Dense)             (None, 4)                 12        
                                                                 
 dense_3 (Dense)             (None, 8)                 40        
                                                                 
Total params: 98
Trainable params: 98
Non-trainable params: 0
_________________________________________________________________


In [ ]:
labelmodel.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 77)                0         
                                                                 
 dense_2 (Dense)             (None, 67)                5226      
                                                                 
 dropout_1 (Dropout)         (None, 67)                0         
                                                                 
 dense_3 (Dense)             (None, 15)                1020      
                                                                 
Total params: 6,246
Trainable params: 6,246
Non-trainable params: 0
_________________________________________________________________


In [ ]:
predictions = autoencoder.predict(dataset)

In [ ]:
predictions_label = labelmodel.predict(label_train)

In [ ]:
predictions

array([[5.7440639e-02, 1.1290244e-01, 3.4359258e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.3058662e-02],
       [5.7366133e-02, 1.1290264e-01, 3.4359375e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.3047099e-02],
       [5.7392001e-02, 1.1290257e-01, 3.4359333e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.3051152e-02],
       ...,
       [4.9858570e-02, 1.1292308e-01, 3.4371093e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.1884809e-02],
       [4.9841404e-02, 1.1292312e-01, 3.4371120e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.1882305e-02],
       [0.0000000e+00, 1.1312897e-01, 3.4489161e-01, ..., 0.0000000e+00,
        0.0000000e+00, 1.7523766e-04]], dtype=float32)

In [ ]:
predictions_label

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 2.5858648e-26, 1.3321836e-30, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 2.5855098e-26, 1.3405953e-30, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [ ]:
idx = np.argmax(predictions_label, axis = 1)

In [ ]:
idx

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.unique(idx)

array([0, 2, 3, 4, 5])

In [ ]:
idx = pd.DataFrame(idx, columns = ['Label'])

In [ ]:
idx

Label
0         0
1         0
2         0
3         0
4         0
...     ...
2920      0
2921      0
2922      0
2923      0
2924      0

[2925 rows x 1 columns]

In [ ]:
change_label = {
          0: 'BENIGN', 
          1: 'Bot', 
          2: 'DDoS', 
          3: 'DoS_GoldenEye', 
          4: 'DoS_Hulk',
          5: 'DoS_Slowhttptest', 
          6: 'DoS_slowloris', 
          7: 'FTPPatator', 
          8: 'Heartbleed',
          9: 'Infiltration', 
          10: 'PortScan', 
          11: 'SSHPatator', 
          12: 'Web_Attack_Brute_Force',
          13: 'Web_Attack_Sql_Injection', 
          14: 'Web_Attack_XSS'
}

In [ ]:
label = idx.replace({'Label' : change_label})

In [ ]:
label

Label
0     BENIGN
1     BENIGN
2     BENIGN
3     BENIGN
4     BENIGN
...      ...
2920  BENIGN
2921  BENIGN
2922  BENIGN
2923  BENIGN
2924  BENIGN

[2925 rows x 1 columns]

In [ ]:
mse = np.mean(np.power(dataset - predictions, 2), axis = 1)

In [ ]:
mse

array([0.0166485 , 0.0166467 , 0.0166472 , ..., 0.0166578 , 0.01665777,
       0.00460733])

In [ ]:
error_df = pd.DataFrame({'reconstruction_error': mse})
error_df.describe()

reconstruction_error
count           2925.000000
mean               0.019709
std                0.019333
min                0.001600
25%                0.016658
50%                0.016665
75%                0.020001
max                0.352816

In [ ]:
#loss

In [ ]:
threshold = 0.018

In [ ]:
threshold

0.018

In [ ]:
predicted_label = tf.math.less(mse, threshold)
predicted_label

<tf.Tensor: shape=(2925,), dtype=bool, numpy=array([ True,  True,  True, ...,  True,  True,  True])>

## Save the result

In [ ]:
dataset = pd.DataFrame(dataset, columns=main_features[0:8])
Z = pd.DataFrame(Z, columns=details[0:6])

In [ ]:
reconstruction = pd.DataFrame(mse, columns=["recon ERR"])

In [ ]:
result = pd.DataFrame(predicted_label, columns=["result"])

In [ ]:
dataset = Z.merge(dataset, how='outer', left_index=True, right_index=True)
dataset = dataset.merge(reconstruction, how='outer', left_index=True, right_index=True)
dataset = dataset.merge(result, how='outer', left_index=True, right_index=True)
dataset = dataset.merge(label, how='outer', left_index=True, right_index=True)

In [ ]:
dataset.columns = ['Timestamp', 'SourceIP', 'SourcePort', 'DestinationIP', 'DestinationPort', 'Protocol', 'FlowDuration', 'FlowBytes', 'FlowPackets', 'FlowIATMean', 'FwdIATMean', 'BwdIATMean', 'ActiveMean', 'IdleMean', 'reconERR', 'result', 'Label']

In [ ]:
dataset

Timestamp       SourceIP  SourcePort  DestinationIP  \
0    2022-02-28 12:32:16  192.168.1.111       55667   52.72.75.234   
1    2022-02-28 12:32:23  192.168.1.111       55669   52.72.75.234   
2    2022-02-28 12:32:30  192.168.1.111       55670   52.72.75.234   
3    2022-02-28 12:32:34  192.168.1.133       60511  192.168.1.111   
4    2022-02-28 12:32:37  192.168.1.111       55672   52.72.75.234   
...                  ...            ...         ...            ...   
2920 2022-02-28 12:42:53  192.168.1.143       51026    224.0.0.252   
2921 2022-02-28 12:40:36  192.168.1.120       63678    224.0.0.252   
2922 2022-02-28 12:32:55  192.168.1.136       57642    224.0.0.252   
2923 2022-02-28 12:39:35  192.168.1.136       56646    224.0.0.252   
2924 2022-02-28 12:42:59  192.168.7.118        8080   192.168.7.22   

      DestinationPort Protocol  FlowDuration  FlowBytes  FlowPackets  \
0                 443      TCP  9.871862e-03   0.000170     0.000033   
1                 443      TCP  9.937070e-03   0.000169     0.000035   
2                 443      TCP  9.927679e-03   0.000169     0.000034   
3                7680      TCP  2.810856e-05   0.000521     0.002222   
4                 443      TCP  9.804844e-03   0.000171     0.000033   
...               ...      ...           ...        ...          ...   
2920             5355      UDP  2.542453e-03   0.000003     0.000010   
2921             5355      UDP  2.552579e-03   0.000005     0.000010   
2922             5355      UDP  2.610171e-03   0.000003     0.000010   
2923             5355      UDP  2.596196e-03   0.000003     0.000010   
2924            55817      TCP  5.000040e-08   0.000000     0.500000   

       FlowIATMean  FwdIATMean    BwdIATMean  ActiveMean  IdleMean  reconERR  \
0     3.953878e-04    0.000752  1.690047e-03         0.0       0.0  0.016648   
1     3.685164e-04    0.000694  1.578144e-03         0.0       0.0  0.016647   
2     3.823293e-04    0.000757  1.579869e-03         0.0       0.0  0.016647   
3     7.017926e-06    0.000013  7.272490e-05         0.0       0.0  0.016446   
4     3.927034e-04    0.000748  1.679751e-03         0.0       0.0  0.016648   
...            ...         ...           ...         ...       ...       ...   
2920  2.545913e-03    0.002546  0.000000e+00         0.0       0.0  0.016658   
2921  2.556052e-03    0.002556  0.000000e+00         0.0       0.0  0.016658   
2922  2.613723e-03    0.002614  0.000000e+00         0.0       0.0  0.016658   
2923  2.599728e-03    0.002600  0.000000e+00         0.0       0.0  0.016658   
2924  1.251711e-08    0.000000  2.215197e-08         0.0       0.0  0.004607   

      result   Label  
0       True  BENIGN  
1       True  BENIGN  
2       True  BENIGN  
3       True  BENIGN  
4       True  BENIGN  
...      ...     ...  
2920    True  BENIGN  
2921    True  BENIGN  
2922    True  BENIGN  
2923    True  BENIGN  
2924    True  BENIGN  

[2925 rows x 17 columns]

In [ ]:
np.unique(dataset["Label"])

array(['BENIGN', 'DDoS', 'DoS_GoldenEye', 'DoS_Hulk', 'DoS_Slowhttptest'],
      dtype=object)

In [ ]:
#dataset.to_json('output.json',orient='table')

## MySQL

In [ ]:
!sudo apt-get install python3-dev default-libmysqlclient-dev
!pip install pymysql

Reading package lists... Done
Building dependency tree       
Reading state information... Done
default-libmysqlclient-dev is already the newest version (1.0.4).
python3-dev is already the newest version (3.6.7-1~18.04).
The following packages were automatically installed and are no longer required:
  libnvidia-common-460 nsight-compute-2020.2.0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.


In [ ]:
import pymysql
from sqlalchemy import create_engine

In [ ]:
pymysql.install_as_MySQLdb()
import MySQLdb

In [ ]:
#engine = create_engine("mysql+pymysql://master:"+"tomatocatchup"+"@webdashboarddb.chrqiv0hwpum.ap-northeast-2.rds.amazonaws.com:3306/webDashboard?charset=utf8",encoding='utf-8')

In [ ]:
#conn = engine.connect()

In [ ]:
#dataset.to_sql(name='Test', con=engine, if_exists='append', index=False )

In [ ]:
#conn.close()